# Generated by Django 5.2.4 on 2025-08-31 00:03

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("voucher_type", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "voucherId",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("voucherNumber", models.CharField(max_length=50, unique=True)),
                ("voucherRemark", models.TextField(default="Remark....")),
                ("onTally", models.BooleanField(default=True)),
                (
                    "created_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 828712, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 828712, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucherCustomer",
                        to="customer.customer",
                    ),
                ),
                (
                    "salesman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucherSalesman",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucherType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucherType",
                        to="voucher_type.vouchertype",
                    ),
                ),
            ],
        ),
    ]
