# Generated by Django 5.2.4 on 2025-08-31 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0004_alter_voucher_created_on_alter_voucher_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="voucherDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
