# Generated by Django 5.2.4 on 2026-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0005_voucher_voucherdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="voucherGUID",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
