# Generated by Django 5.2.4 on 2025-08-31 00:03

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "receiptId",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "paymentMode",
                    models.CharField(
                        choices=[("cash", "cash"), ("bank", "bank")],
                        default="cash",
                        max_length=10,
                    ),
                ),
                (
                    "paymentStatus",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("paid", "paid"),
                            ("cancel", "cancel"),
                        ],
                        default="paid",
                        max_length=20,
                    ),
                ),
                (
                    "paymentDate",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 875589, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("paymentAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("onTally", models.BooleanField(default=True)),
                (
                    "created_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 875589, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 875589, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
