# Generated by Django 5.2.4 on 2025-08-31 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("receipt", "0001_initial"),
        ("voucher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_voucher",
                to="voucher.voucher",
            ),
        ),
    ]
