# Generated by Django 5.2.4 on 2026-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0005_alter_receipt_created_on_alter_receipt_paymentdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="recceiptGUID",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
