# Generated by Django 5.2.4 on 2025-08-31 00:03

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customerId",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("customerCode", models.CharField(max_length=100, unique=True)),
                ("customerName", models.CharField(max_length=100)),
                ("onTally", models.BooleanField(default=True)),
                (
                    "created_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 797464, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 797464, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
