# Generated by Django 5.2.4 on 2025-08-31 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_customer_created_on_alter_customer_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
