# Generated by Django 5.2.4 on 2026-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_customer_created_on_alter_customer_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customerGUID",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
