# Generated by Django 5.2.4 on 2025-08-31 00:03

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "productId",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("productCode", models.CharField(max_length=100, unique=True)),
                ("productName", models.CharField(max_length=100)),
                (
                    "baseUnit",
                    models.CharField(
                        choices=[("kg", "kg"), ("nos", "nos"), ("pcs", "pcs")],
                        default="nos",
                        max_length=20,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 813087, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 813087, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("onTally", models.BooleanField(default=True)),
            ],
        ),
    ]
