# Generated by Django 5.2.4 on 2026-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_created_on_alter_product_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productGUID",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
