# Generated by Django 5.2.4 on 2025-08-31 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_alter_warehouse_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="updated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
