# Generated by Django 5.2.4 on 2026-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_alter_warehouse_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="warehouseGUID",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
