# Generated by Django 5.2.4 on 2025-08-31 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoucherType",
            fields=[
                (
                    "voucherName",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 813087, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 8, 31, 0, 3, 56, 813087, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
