# Generated by Django 5.2.4 on 2025-08-31 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_type", "0002_alter_vouchertype_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchertype",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 0, 7, 9, 466741, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="vouchertype",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 0, 7, 9, 466741, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
