# Generated by Django 5.2.4 on 2025-08-31 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesman", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesman",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 0, 5, 13, 396761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="salesman",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 0, 5, 13, 396761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
