# Generated by Django 5.2.4 on 2025-08-31 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesman", "0002_alter_salesman_created_on_alter_salesman_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesman",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 0, 7, 9, 435490, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="salesman",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 0, 7, 9, 435490, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
