# Generated by Django 5.2.4 on 2025-08-31 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesman", "0003_alter_salesman_created_on_alter_salesman_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesman",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="salesman",
            name="updated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
