# Generated by Django 5.2.4 on 2026-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesman", "0004_alter_salesman_created_on_alter_salesman_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesman",
            name="salesmanGUID",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
